# Generated by Django 2.2.9 on 2022-02-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220210_1758'),
        ('posts', '0006_auto_20220210_1801'),
    ]

    operations = [
    ]
